# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Checkers' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Checkers
pod 'Firebase'
pod 'FirebaseRemoteConfig'
pod 'Google-Mobile-Ads-SDK'
pod 'LTMorphingLabel'
pod 'lottie-ios'

end
